[package]
name = "packeteer"
authors = ["RJ <rj@metabrew.com>"]
version = "0.1.0"
edition = "2021"
description = "A transport layer atop unreliable datagram exchange"

[dependencies]
bytes = "1.5.0"
log = "0.4.20"
env_logger = "0.10.0"

[dev-dependencies]
rand = "0.8.5"